import angular from 'angular';

module.exports = angular.module('app.services', []);
require('./statistics');
require('./map');
require('./seatMap');
require('./chartUser');
require('./chartEmploy');
require('./chartCar');
require('./leaderMap');
require('./socket');
require('./sign');
require('./seatService');
require('./leaderOrderStorageService');
require('./searchOrderStorageService');
require('./policeService');
require('./security');
require('./user');
require('./handleAlarmDialog');
require('./messageBoxService');
require('./socketMessageService');
require('./alarmMessageService');
require('./orderStateChangeMessage');
require('./leaderOrderInfoDialog');
require('./myHttpInterceptor');
