module.exports = angular.module('app.services', []);
require('./statistics');
require('./order');
require('./orderStep');
require('./assign');
require('./map');
require('./seatMap');
require('./login');
require('./chartUser');
require('./chartEmploy');
require('./chartCar');
require('./leaderMap');
require('./user');
require('./orderNotify');
require('./socket');
require('./phone');
