module.exports = angular.module('app.dirctives', []);
require('./seatMapView');
require('./chartUser');
require('./callStatus');
require('./pagination');
require('./wordsPlace');
require('./leaderMap');
require('./chartEmploy');
require('./chartCar');
require('./listenCall');
require('./pauseEmit');
require('./calendar');
require('./handleAlarmOrder');
require('./confirmDialog');
require('./timeSelect');
require('./leaderOrderInfo');
